name: CI - rama mora

on:
  push:
    branches:
      - main  # puedes cambiar a 'mora' si quieres que solo corra en tu rama de apellido

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Instalar Flask compatible con Python 3.11, evitando error por versión 2.3.4
          pip install "Flask>=2.3.0,<2.4.0"
          # Instalar el resto de dependencias de requirements.txt
          pip install -r requirements.txt

      - name: Run tests
        run: |
          # Ejecuta todos los tests con pytest
          python -m pytest -q
